// Downloads Phosphor Icons metadata and generates a reverse index
// mapping search terms to icon names.
//
// Run with: go run scripts/generate-icon-tags.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
)

const iconsURL = "https://raw.githubusercontent.com/phosphor-icons/core/main/src/icons.ts"
const outputPath = "src/js/icon-tags.js"

type Icon struct {
	Name string
	Tags []string
}

func fetch(url string) (string, error) {
	resp, err := http.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(body), nil
}

func parseIconsTs(content string) []Icon {
	var icons []Icon

	// Match each icon object: { name: "icon-name", ..., tags: ["tag1", "tag2"], ... }
	iconRegex := regexp.MustCompile(`\{\s*name:\s*"([^"]+)"[^}]*?tags:\s*\[([^\]]*)\]`)
	tagRegex := regexp.MustCompile(`"([^"]+)"`)

	matches := iconRegex.FindAllStringSubmatch(content, -1)
	for _, match := range matches {
		name := match[1]
		tagsStr := match[2]

		var tags []string
		tagMatches := tagRegex.FindAllStringSubmatch(tagsStr, -1)
		for _, tagMatch := range tagMatches {
			tag := tagMatch[1]
			// Skip meta tags like *new* and *updated*
			if !strings.HasPrefix(tag, "*") {
				tags = append(tags, strings.ToLower(tag))
			}
		}

		icons = append(icons, Icon{Name: name, Tags: tags})
	}

	return icons
}

func buildReverseIndex(icons []Icon) map[string][]string {
	index := make(map[string]map[string]bool)

	for _, icon := range icons {
		// Add icon name parts as searchable terms
		nameParts := strings.Split(icon.Name, "-")
		for _, part := range nameParts {
			if index[part] == nil {
				index[part] = make(map[string]bool)
			}
			index[part][icon.Name] = true
		}

		// Add each tag
		for _, tag := range icon.Tags {
			if index[tag] == nil {
				index[tag] = make(map[string]bool)
			}
			index[tag][icon.Name] = true
		}
	}

	// Convert sets to sorted arrays
	result := make(map[string][]string)
	for term, iconSet := range index {
		var icons []string
		for icon := range iconSet {
			icons = append(icons, icon)
		}
		sort.Strings(icons)
		result[term] = icons
	}

	return result
}

func generateModule(reverseIndex map[string][]string, iconCount int) string {
	jsonBytes, _ := json.MarshalIndent(reverseIndex, "", "  ")

	return fmt.Sprintf(`// Auto-generated by scripts/generate-icon-tags.go
// Source: @phosphor-icons/core (MIT License)
// %d icons, %d search terms
// Run: go run scripts/generate-icon-tags.go

export const iconTags = %s

/**
 * Search for icons by term (exact match against name parts and tags)
 * @param {string} query - Search term
 * @returns {string[]} - Matching icon names
 */
export function searchIcons(query) {
  const term = query.toLowerCase().trim()
  return iconTags[term] || []
}

/**
 * Search for icons matching any of the given terms
 * @param {string} query - Space-separated search terms
 * @returns {string[]} - Matching icon names (union of all matches)
 */
export function searchIconsMulti(query) {
  const terms = query.toLowerCase().trim().split(/\s+/)
  const results = new Set()
  for (const term of terms) {
    for (const icon of (iconTags[term] || [])) {
      results.add(icon)
    }
  }
  return Array.from(results).sort()
}
`, iconCount, len(reverseIndex), string(jsonBytes))
}

func main() {
	fmt.Println("Fetching Phosphor Icons metadata...")
	content, err := fetch(iconsURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error fetching: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Parsing icons...")
	icons := parseIconsTs(content)
	fmt.Printf("Found %d icons\n", len(icons))

	fmt.Println("Building reverse index...")
	reverseIndex := buildReverseIndex(icons)
	fmt.Printf("Generated %d search terms\n", len(reverseIndex))

	fmt.Printf("Writing to %s...\n", outputPath)
	moduleContent := generateModule(reverseIndex, len(icons))
	err = os.WriteFile(outputPath, []byte(moduleContent), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Done!")
}
